"""
CI / Repo Hygiene tests asserting canonical file locations and no reintroduced duplicate root assets.
"""

from pathlib import Path


def test_static_export_hygiene():
    """Assert canonical copies live in ui/ and root static export is present for Hugging Face Spaces."""
    root_dir = Path(__file__).resolve().parent.parent

    # Canonical source copies must exist in ui/
    ui_index = root_dir / "ui" / "index.html"
    ui_static = root_dir / "ui" / "static_data.js"
    assert ui_index.exists(), "ui/index.html missing"
    assert ui_static.exists(), "ui/static_data.js missing"

    # Root export files generated by scripts/build_static.py must exist for static HF Space
    root_index = root_dir / "index.html"
    root_static = root_dir / "static_data.js"
    assert root_index.exists(), "Root index.html missing for static deployment"
    assert root_static.exists(), "Root static_data.js missing for static deployment"


def test_shared_zip_safety_module_exists():
    """Assert agents/zip_safety.py exists and exports assert_zip_entry_is_safe."""
    from agents.zip_safety import assert_zip_entry_is_safe
    assert callable(assert_zip_entry_is_safe)
